package RMAPP;

/**
* RMAPP/RMHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/RM.idl
* Monday, November 22, 2021 6:25:09 o'clock PM EST
*/

public final class RMHolder implements org.omg.CORBA.portable.Streamable
{
  public RMAPP.RM value = null;

  public RMHolder ()
  {
  }

  public RMHolder (RMAPP.RM initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RMAPP.RMHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RMAPP.RMHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RMAPP.RMHelper.type ();
  }

}
