package RMAPP;


/**
* RMAPP/RMOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/RM.idl
* Monday, November 22, 2021 6:25:09 o'clock PM EST
*/

public interface RMOperations 
{
  String sayHello ();
  String createRoom (int roomNumber, String date, String List_Of_Time_Slots, String id, String location);
  String deleteRoom (int roomNumber, String date, String List_Of_Time_Slots, String id, String location);
  String bookRoom (String campusName, int roomNumber, String date, String timeslot, String id, String location);
  String getAvailableTimeSlot (String date, String id, String location);
  String cancelBooking (String bookingID, String id, String location);
  String changeReservation (String bookingID, String campusName, int roomNumber, String timeslot, String date, String id, String location);
  void shutdown ();
} // interface RMOperations
