package RMAPP;


/**
* RMAPP/RMPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/RM.idl
* Monday, November 22, 2021 6:25:09 o'clock PM EST
*/

public abstract class RMPOA extends org.omg.PortableServer.Servant
 implements RMAPP.RMOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("createRoom", new java.lang.Integer (1));
    _methods.put ("deleteRoom", new java.lang.Integer (2));
    _methods.put ("bookRoom", new java.lang.Integer (3));
    _methods.put ("getAvailableTimeSlot", new java.lang.Integer (4));
    _methods.put ("cancelBooking", new java.lang.Integer (5));
    _methods.put ("changeReservation", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // RMAPP/RM/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // RMAPP/RM/createRoom
       {
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String List_Of_Time_Slots = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.createRoom (roomNumber, date, List_Of_Time_Slots, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // RMAPP/RM/deleteRoom
       {
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String List_Of_Time_Slots = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.deleteRoom (roomNumber, date, List_Of_Time_Slots, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // RMAPP/RM/bookRoom
       {
         String campusName = in.read_string ();
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String timeslot = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.bookRoom (campusName, roomNumber, date, timeslot, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // RMAPP/RM/getAvailableTimeSlot
       {
         String date = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.getAvailableTimeSlot (date, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // RMAPP/RM/cancelBooking
       {
         String bookingID = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.cancelBooking (bookingID, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // RMAPP/RM/changeReservation
       {
         String bookingID = in.read_string ();
         String campusName = in.read_string ();
         int roomNumber = in.read_long ();
         String timeslot = in.read_string ();
         String date = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.changeReservation (bookingID, campusName, roomNumber, timeslot, date, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // RMAPP/RM/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RMAPP/RM:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RM _this() 
  {
    return RMHelper.narrow(
    super._this_object());
  }

  public RM _this(org.omg.CORBA.ORB orb) 
  {
    return RMHelper.narrow(
    super._this_object(orb));
  }


} // class RMPOA
