package RSAPP;


/**
* RSAPP/RS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Replica.idl
* Tuesday, November 23, 2021 7:38:25 o'clock PM EST
*/

public interface RS extends RSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RS
