package RSAPP;


/**
* RSAPP/RSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Replica.idl
* Tuesday, November 23, 2021 7:38:25 o'clock PM EST
*/

public interface RSOperations 
{
  String sayHello ();
  String createRoomHere (int roomNumber, String date, String List_Of_Time_Slots, String id, String location);
  String deleteRoomHere (int roomNumber, String date, String List_Of_Time_Slots, String id, String location);
  String bookRoomHere (String campusName, int roomNumber, String date, String timeslot, String id, String location);
  String getAvailableTimeSlotHere (String date, String id, String location);
  String cancelBookingHere (String bookingID, String id, String location);
  void shutdown ();
} // interface RSOperations
