package RSAPP;


/**
* RSAPP/RSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Replica.idl
* Tuesday, November 23, 2021 7:38:25 o'clock PM EST
*/

public abstract class RSPOA extends org.omg.PortableServer.Servant
 implements RSAPP.RSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("createRoomHere", new java.lang.Integer (1));
    _methods.put ("deleteRoomHere", new java.lang.Integer (2));
    _methods.put ("bookRoomHere", new java.lang.Integer (3));
    _methods.put ("getAvailableTimeSlotHere", new java.lang.Integer (4));
    _methods.put ("cancelBookingHere", new java.lang.Integer (5));
    _methods.put ("shutdown", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // RSAPP/RS/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // RSAPP/RS/createRoomHere
       {
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String List_Of_Time_Slots = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.createRoomHere (roomNumber, date, List_Of_Time_Slots, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // RSAPP/RS/deleteRoomHere
       {
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String List_Of_Time_Slots = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.deleteRoomHere (roomNumber, date, List_Of_Time_Slots, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // RSAPP/RS/bookRoomHere
       {
         String campusName = in.read_string ();
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String timeslot = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.bookRoomHere (campusName, roomNumber, date, timeslot, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // RSAPP/RS/getAvailableTimeSlotHere
       {
         String date = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.getAvailableTimeSlotHere (date, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // RSAPP/RS/cancelBookingHere
       {
         String bookingID = in.read_string ();
         String id = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.cancelBookingHere (bookingID, id, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // RSAPP/RS/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RSAPP/RS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RS _this() 
  {
    return RSHelper.narrow(
    super._this_object());
  }

  public RS _this(org.omg.CORBA.ORB orb) 
  {
    return RSHelper.narrow(
    super._this_object(orb));
  }


} // class RSPOA
